/**
 * standards.js — shared 7th-grade standards data + code normalizer.
 *
 * Single source of truth, loaded by BOTH Big Picture (the year's checklist)
 * and Portfolio (the clickable "jump to the work that shows mastery" grid).
 * Codes are the ACTUAL Oregon standards; see the note on the array below.
 */

window.HS_STANDARDS = [
  { area: 'Math', side: 'MATH', color: 'Math', tex: 'tex-a', ghost: 'Math', tagline: 'proportions, algebra, geometry & data', source: 'Oregon 2021 Mathematics Standards · Grade 7', list: [
    { code: '7.NS.A.1', label: 'Add & subtract rational numbers (extend to negatives & absolute value)' },
    { code: '7.NS.A.2', label: 'Multiply & divide rational numbers' },
    { code: '7.NS.A.3', label: 'Write rational numbers as equivalent fractions, decimals & percents' },
    { code: '7.AEE.A.1', label: 'Write equivalent expressions using the properties of operations' },
    { code: '7.AEE.A.2', label: 'Rewriting an expression can show how quantities are related' },
    { code: '7.AEE.B.3', label: 'Solve problems using expressions & equations with positive & negative rationals' },
    { code: '7.AEE.B.4', label: 'Build & solve one- and two-step linear inequalities' },
    { code: '7.RP.A.1', label: 'Unit rates involving ratios of fractions' },
    { code: '7.RP.A.2', label: 'Recognize & represent proportional relationships (tables, graphs, equations)' },
    { code: '7.RP.A.3', label: 'Use proportional relationships to solve ratio & percent problems' },
    { code: '7.RP.B.4', label: 'Probability of a chance event is a number between 0 and 1' },
    { code: '7.RP.B.5', label: 'Use experimental & theoretical probability to make predictions' },
    { code: '7.RP.B.6', label: 'Develop a probability model and use it to find probabilities' },
    { code: '7.RP.B.7', label: 'Probabilities of compound events (lists, tables, tree diagrams, simulation)' },
    { code: '7.GM.A.1', label: 'Scale drawings — compute actual lengths & areas' },
    { code: '7.GM.A.2', label: 'Draw triangles from given angles/sides; when they are possible or unique' },
    { code: '7.GM.B.3', label: 'Relate area & circumference of circles; use the formulas' },
    { code: '7.GM.B.4', label: 'Supplementary, complementary, vertical & adjacent angles' },
    { code: '7.GM.B.5', label: 'Area, volume & surface area of 2-D and 3-D figures' },
    { code: '7.DR.A.1', label: 'Formulate investigative questions; samples must be representative' },
    { code: '7.DR.B.2', label: 'Use random samples to draw inferences about populations' },
    { code: '7.DR.C.3', label: 'Compare two data distributions (center & variability)' },
    { code: '7.DR.D.4', label: 'Interpret center & variability to compare populations' },
  ] },
  { area: 'Science', side: 'SCIENCE', color: 'Science', tex: 'tex-b', ghost: 'Science', tagline: 'matter, Earth & energy', source: 'Oregon (NGSS) Science Standards · Grade 7', list: [
    { code: '7.PS1.1', label: 'Model the atomic composition of molecules & extended structures' },
    { code: '7.PS1.2', label: 'Analyze evidence that a chemical reaction has occurred' },
    { code: '7.PS1.3', label: 'Synthetic materials come from natural resources & impact society' },
    { code: '7.PS1.4', label: 'Particle motion, temperature & state changes with thermal energy' },
    { code: '7.PS1.5', label: 'Conservation of mass — atom count is unchanged in a reaction' },
    { code: '7.PS1.6', label: 'Design a device that releases or absorbs thermal energy' },
    { code: '7.PS3.1', label: 'Kinetic energy relates to the mass & speed of an object' },
    { code: '7.PS3.2', label: 'Potential energy is stored based on position & interaction' },
    { code: '7.PS3.5', label: 'Energy is transferred to or from an object (evidence of change)' },
    { code: '7.ESS2.1', label: "Cycling of Earth's materials & the energy that drives it" },
    { code: '7.ESS2.2', label: "Geoscience processes have changed Earth's surface (time & scale)" },
    { code: '7.ESS2.3', label: 'Evidence for past plate motions (fossils, rocks, seafloor)' },
    { code: '7.ESS3.1', label: "Uneven distribution of Earth's resources from geoscience processes" },
    { code: '7.ESS3.2', label: 'Forecast natural hazards & technologies to mitigate them' },
    { code: '7.LS1.6', label: 'Photosynthesis in the cycling of matter & flow of energy' },
    { code: '7.LS1.7', label: 'Food rearranged through chemical reactions for growth/energy' },
    { code: '7.LS2.1', label: 'Effects of resource availability on organisms & populations' },
    { code: '7.LS2.2', label: 'Predict patterns of interactions among organisms' },
    { code: '7.LS2.3', label: 'Cycling of matter & flow of energy among living & nonliving parts' },
    { code: '7.LS2.4', label: 'Changes to an ecosystem affect its populations (argument)' },
    { code: '7.LS2.5', label: 'Evaluate design solutions for maintaining biodiversity' },
    { code: 'MS.ETS1.1', label: 'Define the criteria & constraints of a design problem' },
    { code: 'MS.ETS1.2', label: 'Evaluate competing design solutions' },
    { code: 'MS.ETS1.3', label: 'Combine the best characteristics of solutions into a better one' },
    { code: 'MS.ETS1.4', label: 'Model to generate data for iterative testing & refinement' },
  ] },
  { area: 'Reading & Writing', side: 'ELA', color: 'ELA', tex: 'tex-c', ghost: 'Reading', tagline: 'read closely, write to argue, inform & tell', source: 'Oregon English Language Arts · Grade 7', list: [
    { code: '7.RL.1', label: 'Literature: cite several pieces of textual evidence (explicit & inferred)' },
    { code: '7.RL.2', label: 'Literature: determine a theme & analyze its development; summarize' },
    { code: '7.RL.3', label: 'Literature: analyze how story/drama elements interact' },
    { code: '7.RL.4', label: 'Literature: meaning of words/phrases; impact of rhyme & sound' },
    { code: '7.RL.5', label: "Literature: how a drama's or poem's form contributes to meaning" },
    { code: '7.RL.6', label: 'Literature: analyze & contrast points of view of characters/narrators' },
    { code: '7.RL.7', label: 'Literature: compare a text to its audio/film/staged version' },
    { code: '7.RL.9', label: 'Literature: compare a fictional portrayal with a historical account' },
    { code: '7.RL.10', label: 'Literature: read & comprehend grades 6–8 texts proficiently' },
    { code: '7.RI.1', label: 'Informational: cite several pieces of textual evidence' },
    { code: '7.RI.2', label: 'Informational: determine two+ central ideas; summarize' },
    { code: '7.RI.3', label: 'Informational: analyze interactions of individuals, events & ideas' },
    { code: '7.RI.4', label: 'Informational: figurative, connotative & technical word meaning' },
    { code: '7.RI.5', label: 'Informational: analyze the structure used to organize a text' },
    { code: '7.RI.6', label: "Informational: author's point of view & purpose" },
    { code: '7.RI.7', label: 'Informational: compare a text to an audio/video/multimedia version' },
    { code: '7.RI.8', label: 'Informational: trace & evaluate an argument and its evidence' },
    { code: '7.RI.9', label: 'Informational: analyze how two authors treat the same topic' },
    { code: '7.RI.10', label: 'Informational: read & comprehend grades 6–8 texts proficiently' },
    { code: '7.W.1', label: 'Write arguments with claims, reasons & evidence' },
    { code: '7.W.2', label: 'Write informative / explanatory texts' },
    { code: '7.W.3', label: 'Write narratives' },
    { code: '7.W.4', label: 'Produce clear, coherent writing for task, purpose & audience' },
    { code: '7.W.5', label: 'Plan, revise, edit & rewrite to strengthen writing' },
    { code: '7.W.6', label: 'Use technology to produce, publish & link to sources' },
    { code: '7.W.7', label: 'Conduct short research projects from several sources' },
    { code: '7.W.8', label: 'Gather & assess sources; quote/paraphrase; avoid plagiarism; cite' },
    { code: '7.W.9', label: 'Draw evidence from texts to support analysis & research' },
    { code: '7.W.10', label: 'Write routinely over extended & shorter time frames' },
    { code: '7.SL.1', label: 'Engage effectively in collaborative discussions' },
    { code: '7.SL.2', label: 'Analyze main ideas in diverse media & formats' },
    { code: "7.SL.3", label: "Delineate a speaker's argument; evaluate reasoning & evidence" },
    { code: '7.SL.4', label: 'Present claims & findings with relevant evidence' },
    { code: '7.SL.5', label: 'Include multimedia & visual displays in presentations' },
    { code: '7.SL.6', label: 'Adapt speech to context; use formal English when appropriate' },
    { code: '7.L.1', label: 'Command of grammar & usage when writing/speaking' },
    { code: '7.L.2', label: 'Command of capitalization, punctuation & spelling' },
    { code: '7.L.3', label: 'Use knowledge of language & its conventions' },
    { code: '7.L.4', label: 'Determine word meaning (context, roots/affixes, references)' },
    { code: '7.L.5', label: 'Figurative language, word relationships & nuance' },
    { code: '7.L.6', label: 'Acquire & use grade-level academic & domain vocabulary' },
  ] },
  { area: 'Social Studies', side: 'HISTORY', color: 'Humanities', tex: 'tex-d', ghost: 'History', tagline: 'civics, geography, economics & history', source: 'Oregon 2024 Social Science Standards · Grade 7', list: [
    { code: '7.C.PI.1', label: 'Civics: early governance, Paleolithic to 900 CE' },
    { code: '7.C.PI.2', label: 'Civics: governance after 600 CE & treatment of underrepresented groups' },
    { code: '7.C.PI.3', label: 'Civics: compare historical & modern governance across continents' },
    { code: '7.C.PI.4', label: 'Civics: religions, philosophies & legal systems on rights & justice' },
    { code: '7.C.PI.5', label: 'Civics: constitutions, laws, treaties & international agreements' },
    { code: '7.C.IR.6', label: 'Civics: rights & roles of citizens to 900 CE' },
    { code: '7.C.IR.7', label: 'Civics: rights & roles of citizens after 600 CE' },
    { code: '7.C.IR.8', label: 'Civics: resisting misinformation, indifference & discrimination' },
    { code: '7.C.DP.9', label: 'Civics: repair, reconciliation & restorative justice after injustice' },
    { code: '7.C.CE.10', label: 'Civics: attempts to limit the power of government' },
    { code: '7.G.GR.1', label: 'Geography: maps & spatial thinking on movement of people, goods, ideas' },
    { code: '7.G.GR.2', label: 'Geography: place, region, absolute & relative location' },
    { code: '7.G.MM.3', label: 'Geography: transport & communication spread ideas & culture' },
    { code: '7.G.HI.4', label: 'Geography: how place shapes culture, politics, religion, identity' },
    { code: '7.G.HI.5', label: 'Geography: consequences of cultural conflict, exchange & fusion' },
    { code: '7.G.HE.6', label: 'Geography: how environment shapes population, tech & resource use' },
    { code: '7.G.HE.7', label: 'Geography: how conquest & colonialism affected communities' },
    { code: '7.E.ES.1', label: 'Economics: education/training for two career choices' },
    { code: '7.E.ES.2', label: 'Economics: budget for living expenses & savings' },
    { code: '7.E.ES.3', label: 'Economics: tools to budget & save for a large purchase' },
    { code: '7.E.MI.4', label: 'Economics: supply & demand affect wages & prices' },
    { code: '7.E.MI.5', label: 'Economics: roles of consumers & producers in markets' },
    { code: '7.E.MI.6', label: 'Economics: the four factors of production' },
    { code: '7.E.MI.7', label: 'Economics: how different economic systems allocate resources' },
    { code: '7.E.IC.8', label: 'Economics: how government interventions (taxes, tribute) affect people' },
    { code: '7.E.IC.9', label: 'Economics: weigh costs & benefits for underrepresented groups' },
    { code: '7.E.ST.10', label: 'Economics: compare specialization & trade in two civilizations' },
    { code: '7.E.ST.11', label: 'Economics: specialization & the cost of goods for trade/barter' },
    { code: '7.E.ST.12', label: 'Economics: interdependence & technology raise living standards' },
    { code: '7.H.CH.1', label: 'History: construct & interpret a timeline of human societies' },
    { code: '7.H.CH.2', label: 'History: what defines a complex society or "civilization"' },
    { code: '7.H.CH.3', label: 'History: key features of civilizations, Neolithic to 900 CE' },
    { code: '7.H.CC.4', label: 'History: sources on interactions of cultures, Neolithic to 900 CE' },
    { code: '7.H.CC.5', label: 'History: sources on interactions of cultures after 600 CE' },
    { code: '7.H.CC.6', label: 'History: Indigenous resilience & resistance to colonialism' },
    { code: '7.H.CE.7', label: 'History: how conquest & colonialism affected communities' },
    { code: '7.H.CP.8', label: 'History: origins of early world religions, Neolithic to 1500 CE' },
    { code: '7.H.CP.9', label: 'History: creation & origin stories across cultures' },
    { code: '7.H.CP.10', label: 'History: compare Hinduism, Judaism, Buddhism, Taoism, Christianity, Islam' },
    { code: '7.H.CP.11', label: 'History: origins & modern forms of anti-Judaism' },
    { code: '7.H.CP.12', label: 'History: how institutions create or address injustice' },
    { code: '7.H.CP.13', label: 'History: Indigenous civilizations of the Americas, to 1500' },
    { code: '7.H.CP.14', label: 'History: cultures of W. Asia, Middle East & N. Africa, to 1500' },
    { code: '7.H.CP.15', label: 'History: cultures of Sub-Saharan Africa' },
  ] },
];

/* Normalize a standard code so codes in different formats still match, e.g.
   "MS-ESS3-1", "7.ESS3.1" → "ESS31"; "RI.7.1", "7.RI.1" → "RI1". */
window.hsNormStd = function norm(code) {
  let c = (code || '').trim().toUpperCase().replace(/\s+/g, '');
  c = c.replace(/^MS[-.]?/, '');   // MS-ESS3-1 -> ESS3-1
  c = c.replace(/^7\./, '');       // 7.RI.1 -> RI.1 ; 7.ESS3.1 -> ESS3.1
  c = c.replace(/\.7\./, '.');     // RI.7.1 -> RI.1
  c = c.replace(/-/g, '.');        // ESS3-1 -> ESS3.1
  return c.replace(/\./g, '');     // -> ESS31, RI1
};
